import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { fetchEntries } from "../util/contentfulPosts";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <pre>{JSON.stringify(posts, null, 2)}</pre> */}

        {posts.map(post => (
          <h1 key={post.id} className={styles.title}>
            <Link href={`/posts/${post.id}`}>
              <a>{post.title}</a>
            </Link>
          </h1>
        ))}
        <Image
          src="/images/profile.jpg"
          width={144}
          height={202}
          alt="Your Name"
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetchEntries();

  const posts = await res.map(p => {
    return p.fields;
  });

  return {
    props: {
      posts,
    },
  };
}
